language: node_js
node_js:
  - "10"
branches:
  only:
  - master
before_install:
  - sudo apt-get install libpng-dev
  - sudo apt-get install nasm
  - npm install -g firebase-tools
  - npm install -g webpack-cli
  - npm install -g webpack
  - npm install -g hexo
  - npm install
install:
  - npm install
script:
  - hexo clean
  - hexo generate
  - hexo deploy
  - cd themes/leeboonstra/design
  - npm install
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN2