deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN3"
  project: "leeboonstra-dev-7d578"
language: node_js
node_js:
  - "12"
branches:
  only:
  - master
before_install:
  - sudo apt-get install libpng-dev
  - sudo apt-get install nasm
  - npm install -g firebase-tools
  - npm install -g webpack-cli
  - npm install -g webpack
  - npm install -g workbox-cli
  - npm install js-yaml@latest
  - npm install hexo-cli -g
  - npm install -g hexo@6.0.0
install:
  - npm install --force
script:
  - hexo clean
  - hexo deploy
  - cd themes/leeboonstra/design
  - npm install
  - cd ../../../
  - workbox generateSW workbox-config.js
after_success:
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN3"