language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_install:
- sudo apt-get install libpng-dev
- sudo apt-get install nasm
- npm install -g hexo
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
  deploy:
    provider: firebase
    token:
      secure: V4LG/HExW9zJ80Zx9qL6CnKnZCKMHIZKSsbdHi/rxwh5Lj8WKj59ebuM3aTLgcoiniyogOjZkE9yMzWiIIOMC9Abb+RGCU/SX2B3QaaFbQYxciPY4hWSqFlT28adhkV7lBjxbVTYFU1DeNU0d1UZz4nq9Fo9KDL8XNgRJGCaDP/A7lD4N39kX+Xex37Px0EubKjNfHfwq148a4lLJv46a6MPeV17AUK6J1/oHNl1hGMxrBG37DPlETIcYofBfj2Lq5dhIMifMaAk7dFG9fRHZ6aUd0xqWqRI3ltMeMEt1sbj+fOEafYeVJd5ZFtJNltYSHWzWvfwpyxDU9GBym5HIS2LS8HZ+o3mHFbHE6iUqLX9Ss91dtBFqq7w9mZ9vAiQbJHlYqHU0I63j4lPm3lmXWEC7RVkI6C/p8X6Brp8hm6lM0FSE+EEMXzNES6VuXfmt3kj671qvauALGaA0fKmXgvpqmHqYyDYtJvX8FH1iXJdhYlx/1xtkx1cCQdSaa3EIZjaC2MDbP7fTBWPEWANtKA0EmJRZ5LuTP3iQlMCrQR+Fx0BNokzsH7K5naq5PkEEdYubI7ACfrsQhNK1n3m7uT4un+sW0nI7XGyCglpwS61XGWcdIMvudeNOGkKJ6WTb8QB73qYOqoo4R5o3DZDCJ+Z9OBtcMD4apPUoeQz60k=
    message: "TRAVIS BUILD"
