language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_install:
- sudo apt-get install libpng-dev
- sudo apt-get install nasm
- npm install -g hexo
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
  deploy:
    provider: firebase
    token:
      secure: "rC5DDhG4fAgZz9IQknQmwPRfEk27ss8U7kzJLLThaqGc84rGxc55wxQdLiJaxPeLWGT3axH0MgaVLDdI0GiHVOu7EoVlsaXc3GIKNME9WcK4libRSpb+nZgjo0Bxh7QAaRLMSxJSs07Q09i5TBP6ffD3FCjhePw72G/AMkrNcdtOoHI5KM1eysLuYR1i235yOX5r1KrS8hK9xEcGRloXMvyNOBN/XD0udkv7vbct+wjkKbQV70NaxtljwsNmyJ8matNAnb9HKXU/ty1zwGZ6xAsDPbQCiQuJw/1BJNut+DEVbos5SvYvU12U9cuQ2Ndm7QssZgBsBMo331xC2ILCCinNIu4IRXVRKKDNsZwbuYlka/HDHXtWibuSGFR2OeedZ9EKnCOybC606AnfYtjw9UdKxxYhQXao2Iir1tNkdCcwmRedQmpiBzMKt7n7KnVDWpMlDxgHLhS/6tMAAGq8EvxGzgnpJDH0hkLkXfk4OzC3VensBeiV83tzci6/VoIZIn88TRHW1SeePRELlSNFguWPeazQ1SDuItUZNeK7p35DlSEmp8S0KpbWofoV4wa/y0rHknEWxwyY/OlifmRDJOAR12vcPQULEqBQblXla1kwMFlv7AkI82r9jMXeIENshadsZYKoRMhz+Dl7w6WeoRcSh8THiLqQse4ZAzOHnYw="
