language: node_js
node_js:
  - "12"
branches:
  only:
  - master
before_install:
  - sudo apt-get install libpng-dev
  - sudo apt-get install nasm
  - npm install -g firebase-tools
  - npm install -g webpack-cli
  - npm install -g webpack
  - npm install -g workbox-cli
  - npm install js-yaml@4.0.0
  - npm install hexo-cli -g
  - npm install -g hexo
  - npm install --force
install:
  - npm install --force
script:
  - hexo clean
  - hexo deploy
  - cd themes/leeboonstra/design
  - npm install
  - cd ../../../
  - workbox generateSW workbox-config.js
after_success:
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN3"