language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_install:
- sudo apt-get install libpng-dev
- sudo apt-get install nasm
- npm install -g hexo
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
  deploy:
    provider: firebase
    token:
      secure: "f90nG4LigYylHi7R/Sw95DIMnTeF2u8L/nC+1RbRf+kdY8fh7Mmn5M4V4bSkG3WSeurcFalWu2uIzlJAdGp7oPMFf23BVKQPnmV5Q+1qUBVGjpJJf5tekjKalj2D0JdxXth52sSiIBUBIYqVAyd7D46h0waZ4BhfhUv1pjcQQFoJPE3VZUAgLBrW2C7SGHnFXME3UxUg/WzXmf8mYi78BT2fpgaZANok+qYwrtEO4H2I4F4HNP3mz95liiN2q6Xp7C85n+XiFkZLjTD5Z7Up7TWoLErGgBfwviv04byZhWqpweSE44VccodJzFV3YWQgebYicwHZ1/tqc3yJTCYsTRkjqlXXmm/c1Hl43xeCwEFf4PXheilhnR3af298gF0vpD38qkDxRj0viFPWTOv4iKqKfeTm9apXBS5kW5Hbpm3+MifBit7BnIiWfWu8hRVmpPPqnjkENWhdp2p6CLBNMJdJ1DF5Nvz2LTeMtSZqbRr1syNpSC/cmz548GhuoLWHgZnS6ylGrfivS70BJcpU21CTTdBtc5+uO4Ysnm8ULtjv5oIjCq8G32UT42TcNQr6lqIE5ndeFE4r23DhPR4n4yS8ywSzKn0L+3ompSzzADGaOwltFiWh877nVQzb1MQO8iZEFaodjNqGHGvqolk0T7mZSVYAHJCMDQ4MdQJ+Bx8="
