# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LeeBoonstra.dev | Developer blog
subtitle: <span>"</span> <span>Hi my name is <b>Lee</b>.</span><br><span>I'm a developer advocate, a writer, an engineer, a trainer and a public speaker.</span><br> <span>I create fixes & I fix headaches...</span><br> <span>Welcome to my <b>dev blog</b>.</span><span>"</span>
description: Developer blog of senior developer advocate & Googler; Lee Boonstra. Ex Sencha trainer. Learn more about Chatbots, Dialogflow, Conversational AI, Contact Center AI, Customer Care, Google Assistant. O'Reilly book author of the book Hands-on Sencha Touch 2 and public speaker. Ex-Sencha technical trainer.
keywords: Googler, Dialogflow, JavaScript, Contact Center AI, Customer Care, Chatbots, Voicebots, Conversational AI, Ext JS, Sencha Touch, Cordova, Machine Learning, AI, ML, Machine Learning for Developers, Cloud, GCP, Public Cloud, Ext JS engineer, Google Sales Engineer, Public Speaker, Google Customer Engineer, Googler Engineer, Sencha Sales Engineer, Sencha Trainer, Dev-ops, Dev-ops Specialist, Public Speaker, Machine Learning Public Speaker, Cloud Architect, Devrel, Developer Relations, Developer Expert, Chatbot expert, Actions on Google, Dialogflow expert, Google Cloud Sales, GCP Engineer, Sencha Trainings, JavaScript Developer, Front-end Developer, Lead front-end developer, Client-side Developer, O'Reilly book author, JavaScript Programmer, Node JS Developer, Client-side code, Lead Developer JavaScript Amsterdam, JavaScript Evangelist, Google Assistant Expert, Chatbot Expertise, Chatbot Help, Cloud Help, GCP Help, Google Cloud Solutions, Google Cloud Consultant, Dialogflow Enterprise, Bots Chat agents, HTML5 & CSS3, Sencha Touch Mobile Apps, Enterprise App developer
author: Lee Boonstra
language: en
timezone: Europe/Amsterdam

#Header
menu:
  Home: index.html
  Bio: about/
  Speaking: speaking/
  Abstracts: abstracts/
  Writing: writing/
  Videos: videos/
  Contact: contact/
rss: /atom.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://0.0.0.0:4000/
root: /
permalink: :category/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

sitemap:
    path: sitemap.xml

# widget behavior
archive_type: 'monthly'
show_count: true

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
prism_plugin:
  mode: 'realtime'    # realtime/preprocess
  theme: 'atom-dark'
  line_number: false    # default false
  no_assets: false
highlight: 
  enable: false
  line_number: false
  auto_detect: false

  
# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

index_generator:
  path: ''
  per_page: 5
  order_by: -date
  pagination_dir: page

# hexo-hide-posts
hide_posts:
  # Change the filter name to fit your need
  filter: hidden
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: [category, sitemap, feed, tag, paginator]
  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines
  noindex: false

# Miscellaneous
google_analytics: 'UA-85081556-1'

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: leeboonstra

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''
