# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dialogflow & Conversational AI blog by Google Developer Advocate Lee Boonstra
subtitle: Hi my name is Lee. I'm a senior Developer Advocate, a writer, an engineer, a trainer and a public speaker.</span><br> <span>I create fixes & I fix headaches... Welcome to my dev blog.
description: Conversational AI Blog of Google Developer Advocate & Applied AI Engineer Lee Boonstra. Writes about Dialogflow, Chatbots, NLP and AI in Contact Centers.
keywords: Dialogflow, Dialogue Flow, DialogueFlow, Dialog Flow, Chatbot platform, Bot Builder, Googler, Google developer advocate, O'Reilly Author, Writer, Apress Author, Applied AI Engineer, Contact Center AI, CCAI, Dialogflow CX, Dialogflow Essentials, Conversational AI, Speech, STT, TTS, NLP, NLU, NLP Tools, Google engineer, Conversational AI blog, Chatbot Case Studies, Voice bots, Voice Assistant, Google Assistant, Bot platform, Chat analytics, BERT, Chatbot with AI, Chatbot without coding
author: Lee Boonstra
language: en
timezone: Europe/Amsterdam

#Header
nav:
  Home: index.html
  Bio: about/
  Speaking: speaking/
  Abstracts: abstracts/
  Writing: writing/
  Videos: videos/
  Contact: contact/
rss: /atom.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.leeboonstra.dev
#url: http://localhost:4000
root: /
permalink: :category/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

sitemap:
    path: sitemap.xml
    rel: true
    template: sitemap_template.xml
    tags: true
    categories: true

# widget behavior
archive_type: 'monthly'
show_count: true

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
prism_plugin:
  mode: 'realtime'    # realtime/preprocess
  theme: 'atom-dark'
  line_number: false    # default false
  no_assets: false
highlight: 
  enable: false
  line_number: false
  auto_detect: false

# Image generation
responsive_images:
  priority: 1
  pattern: 'images/**.+(png|webp|jpg)'
  sizes:
    small:
      width: 200
      quality: 50
    medium:
      width: 500
      quality: 65
    large:
      width: 700
      quality: 75
    thumb:
      width: 270
      height: 100
      fit: cover
      quality: 50

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

index_generator:
  path: ''
  per_page: 5
  order_by: -date
  pagination_dir: page

# hexo-hide-posts
hide_posts:
  # Change the filter name to fit your need
  filter: hidden
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: [category, sitemap, feed, tag, paginator]
  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines
  noindex: false

# Miscellaneous
google_analytics: 'UA-85081556-1'

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  autodiscovery: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: false

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: leeboonstra

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

uglify:
  mangle: true
  output:
  compress: true
  es6: false

html_prettify:
  enable: true
  exclude:
      - "*/**/test"
  options:
      indent_size: 1
      indent_char: " "
      max_preserve_newlines: "-1"
      preserve_newlines: false
      keep_array_indentation: true
      break_chained_methods: false
      indent_scripts: normal
      brace_style: expand
      space_before_conditional: true
      unescape_strings: false
      jslint_happy: true
      end_with_newline: true
      wrap_line_length: "0"
      indent_inner_html: false
      comma_first: false
      e4x: false
      indent_empty_lines: false

webpconfig:
  quality: 80
  height: 0
  width: 0

related_posts:
    enabled: true
    filter_threshold: 0.2
    related_count: 5
    weight:
        title: 0.9
        description: 0.8
        keywords: 0.6
        tags: 0.6
        categories: 1
        text: 0.5
    stemmers:
      - en
    reserved:
      - console.dialogflow.com
      - console.cloud.google.com
      - google.com
      - leeboonstra.dev